### ISSUE TITLE
Add eslint support

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/WebsiteOne-FE#12]
Add eslint to the mix to ensure we have consistent code

**Comment by joaopapereira** [comment]
Let's add eslint in the code and also in the test/build process so it gets checked automatically by CI

**Comment by FedericoEsparza** [comment]
I think we'll still be going with standardjs.com
You can follow instructions there.
 
Here's the link to the files changed in the `websiteone-avf` repo: https://github.com/AgileVentures/agile-ventures-website-react-front-end/pull/69/files
Look at `package.json`only
