### ISSUE TITLE
Create Component For React HTML Parser

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/WebsiteOne-FE#124]
Create a component for ReactHTMLParser and pass the content to be parsed down as props. 
## Expected Behavior

Have only one component that imports and uses ReactHTMLParser and re use it for all the components that needs it
## Current Behavior

 The ReactHtmlParser is imported in all the components that need it and this creates duplicate code.

## Possible Solution

Refactor code to have only one componet for the ReactHtmlParser and have this reused in other components that need it.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by mattwr18** [comment]
Not sure we want to do this or not @aonomike, what would the benefit be in this case?
