### ISSUE TITLE
Migrate to new project management board

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/WebsiteOne-FE#148]
Waffle is closing in two months

**Comment by mattwr18** [comment]
we will discuss alternatives in the #anvil meeting

**Comment by arku** [comment]
@arku What do you think of closing this issue as we have started using Github Projects?

**Comment by mattwr18** [comment]
yes, I thought maybe I had done so... :confused:

**Comment by arku** [comment]
@mattwr18  No worries.
