### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/WebsiteOne-FE#168]
## Expected Behavior

There should be a footer with nav links
## Current Behavior

there is only a navbar
## Possible Solution

There is a `PR` @Kachulio1 created that does most of the hard work... maybe one can copy and paste his work and make some small css improvements?
See https://github.com/AgileVentures/WebsiteOne-FE/pull/137

![Screenshot at 2019-03-26 00:15:19](https://user-images.githubusercontent.com/26943915/55419659-9d364b00-554b-11e9-85e7-d6d00c8c39a1.png)

**Comment by arku** [comment]
@mattwr18 I would like to work on this one.

**Comment by mattwr18** [comment]
great, thanks @arku
