### ISSUE TITLE
Video play icons too large

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/WebsiteOne-FE#169]
## Expected Behavior

There should be icons to play the video, but they should be proportional to the size of the embedded video
## Current Behavior

we have had the feedback that they are not proportional
## Possible Solution

Not really sure, as we are using an image as a placeholder
## Steps to Reproduce (for bugs)

1. visit the `/users/3`
2. see the videos in the right column of the page
![Screenshot at 2019-04-02 13:37:04](https://user-images.githubusercontent.com/26943915/55420257-f488eb00-554c-11e9-8e12-d590e065762f.png)

relevant code 
```
<Embed
              id={video.yt_video_id}
              placeholder={
                'https://img.youtube.com/vi/' +
                        video.yt_video_id +
                        '/3.jpg'
              }
              source='youtube'
            />
```

**Comment by clementkng** [comment]
I would like to take a stab at this issue. I'm pretty new to open source and have set up the project to work locally. Haven't read too much into this issue, but could this be solved with some custom CSS to resize the image proportionally?

**Comment by mattwr18** [comment]
hey that is great @clementkng, I don't know if it is that straightforward because if you look at this :point_up: 
```
 placeholder={
                'https://img.youtube.com/vi/' +
                        video.yt_video_id +
                        '/3.jpg'
              }
```
I think we might need to see what the different options for these image placeholders and see if there is one that has a smaller icon, or a different solution.

**Comment by clementkng** [comment]
@mattwr18 I can try looking to see if there is a smaller icon. I was able to shrink them by modifying the `semantic.css` file, but not sure if that's the best practice. However, the tests still pass and as far as I can tell, nothing else changed in the frontend

**Comment by mattwr18** [comment]
that might not be a bad thing, we are using some custom css for semantic anyways... could you push up the code and put in a `PR` so we can have a look and give a review @clementkng?

**Comment by clementkng** [comment]
@mattwr18 Are there videos that are of a different size in this project? Also, should the video icons respond to the width of the page ie shrink along with the page when it is shrunk?
