### ISSUE TITLE
Make Navbar mobile responsive

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/WebsiteOne-FE#170]
## Expected Behavior

Maybe the navbar should collapse into a hamburger when it reaches mobile breakpoints?
## Current Behavior

Currently, the navbar takes up half the screen in mobile view
## Possible Solution

Collapse into a click-able hamburger
## Steps to Reproduce (for bugs)

1. go to the site
2. right-click to inspect
3. click on the mobile link

## Context

It would be nice to develop the site to look good on mobile since lots of people use their phones to browse internet sites
![Screenshot at 2019-04-02 18:17:03](https://user-images.githubusercontent.com/26943915/55437370-1ac28100-5575-11e9-8363-baa401795cb7.png)

**Comment by ALau2088** [comment]
@mattwr18 . Hey Matt. While I am waiting for the create project component to be ready to proceed with the edit project component, I can take on this issue if there is not anyone currently doing so. Let me know. Thanks.

**Comment by arku** [comment]
@ALau2088 Just assigned it to you. Let us know if you need any help.

**Comment by mattwr18** [comment]
That's great! Thanks @ALau2088
