### ISSUE TITLE
User cards' titles overflow when reaching mobile breakpoints

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/WebsiteOne-FE#171]
## Expected Behavior

They would adjust their CSS to handle mobile breakpoints
## Current Behavior

The user's names overflow, breaking the CSS
## Possible Solution

we are using Semantic UI React, and the cards are inside a <Grid>, one of the props is `stackable`, which according to the docs, "A grid can have its columns stack on-top of each other after reaching mobile breakpoints." https://react.semantic-ui.com/collections/grid/
## Steps to Reproduce (for bugs)

1. go to `/users`
2. right-click and choose inspect
3. click on the mobile view

## Context

Looking good on mobile will encourage more people to visit the site on mobile
![Screenshot at 2019-04-02 18:16:51](https://user-images.githubusercontent.com/26943915/55437693-e26f7280-5575-11e9-9dbf-5142a4e859a3.png)

**Comment by 47analogy** [comment]
unable to reproduce (no user cards are currently displaying)
