### ISSUE TITLE
Refactor Create New Project to use redux-form

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/WebsiteOne-FE#187]
Refactor the create project feature to use 'redux-forms' instead of implementing the new form.
## Expected Behavior

Create new project implementation  should completely be implemented using redux-forms
## Current Behavior

The create new project is implements redux
## Possible Solution

Replace redux with redux form

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by jmpainter** [comment]
I'm taking a look at this and am not seeing an existing create project feature - is there a route and component for this already?

**Comment by chris110408** [comment]
i do do think add redux-form to this project is a good practice. it mutate the store of redux directly and create the side effect. we should avoid any tool which could pollute the store.   i think it will bring more headache for this project for the long run.  the
 article talk about the pros and cons of  redux form is as following.  https://blog.scottlogic.com/2018/06/11/pros-cons-of-redux-form.html
