### ISSUE TITLE
Hide Issue Tracker Card on Project Info Page when Projects doesnt have Issue Trackers

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/WebsiteOne-FE#192]
The issue Tracker Card on the Project Info Page should not be displayed when a project does not have issue trackers. 
## Expected Behavior

* Issue Tracker Card is displayed when Project has Issue Trackers associated
* Issue Tracker Card is displayed when Project has Issue Trackers associated
## Current Behavior

* Issue Tracker Card is displayed both when Project has Issue Trackers associated and when Project does not have issue tracker associated
## Possible Solution

* Check to see if Project has issue trackers associated and display or hide it based on that
## Steps to Reproduce (for bugs)
<img width="772" alt="Screen Shot 2019-04-18 at 6 19 35 PM" src="https://user-images.githubusercontent.com/1543546/56372176-28c80100-6207-11e9-8d94-a0f86d26a49f.png">

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by mattwr18** [comment]
closed by https://github.com/AgileVentures/WebsiteOne-FE/pull/197
