### ISSUE TITLE
Hide Members Card on Project Info Page when Projects doesnt have Members

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/WebsiteOne-FE#193]
The Member Card on the Project Info Page should not be displayed when a project does not have members associated.
## Expected Behavior

* Member Card is displayed when Project has Members associated
* Member Card is displayed when Project has Members associated
## Current Behavior

* Member Card is displayed both when Project has Members associated and when Project does not have members associated
## Possible Solution

Check to see if Project has members associated and display or hide it based on that
## Steps to Reproduce (for bugs)

<img width="772" alt="Screen Shot 2019-04-18 at 6 19 35 PM" src="https://user-images.githubusercontent.com/1543546/56372922-9fb1c980-6208-11e9-8d3c-3a9dfff6bd7f.png">

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by mattwr18** [comment]
closed by https://github.com/AgileVentures/WebsiteOne-FE/pull/197
