### ISSUE TITLE
Add ability to add multiple issue trackers on the project's form

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/WebsiteOne-FE#202]
When creating a project, users need to be able to one or more issue trackers associated to their projects. On the create new projects form, add an Input field to capture an issue tracker url plus an ability to add more or remove already added ones.
## Expected Behavior

* Add an input field to add issue tracker urls
* Validate to check that only valid urls are added via the input field
* Add a button to add more issue tracker
* Add button to remove issue tracker
## Current Behavior

The Create Project Page does not have ability to add issue trackers

## Possible Solution

* Add a component for adding issue trackers
* user regular expression to validate that valid url has been added to field before submit
* Add button to add more and remove issue trackers
Below is the current implementation on website one that could be used as a guide
<img width="859" alt="Screen Shot 2019-04-20 at 2 56 42 AM" src="https://user-images.githubusercontent.com/1543546/56448473-24d7d400-6318-11e9-98dc-0a6c99ec4c6b.png">

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by mattwr18** [comment]
closed by https://github.com/AgileVentures/WebsiteOne-FE/pull/219
