### ISSUE TITLE
Add form field to add slack channel name on Create New Project form

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/WebsiteOne-FE#204]
On the create new project form, add a Form input field to add slack_channel_name
## Expected Behavior

- Add Form input field to add slack_channel_name
- Add a label next to the Input field  displaying slack_channel_name
## Current Behavior

There is no form input field for slack channel name.
## Possible Solution

Add Semantic UI react Form.Input to add Input to add field to the form

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by chris110408** [comment]
the createProjectAction.test has problem moxios use the wrong data it will always return a success. fixing it now
