### ISSUE TITLE
Add Button in projects index page that links to the create new project page

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/WebsiteOne-FE#218]
On the projects index page `/projects`, there should be a button that links to the create new project page `/project/new/` 
## Expected Behavior

A button on `projects` projects page which when clicked pushes the user to `projects/new` page
## Current Behavior

There is no link in the `projects` page that pushes user to the `projects/new` page
## Possible Solution

Use react-router-dom Link tag `<Link to={'projects/new'} className='ui button'> Add New Project </Link>`

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by aonomike** [comment]
@mattwr18 seems this has already been implemented. I think we can reframe it to a refactor ticket where we can have a re-usable new-link-button.

**Comment by mattwr18** [comment]
hey @aonomike, this can be closed, no?
do you know what `PR` closed it?
