### ISSUE TITLE
Refactor ProjectForm to make use of two columns of fields

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/WebsiteOne-FE#249]
## Expected Behavior

There should be two columns of fields(input, selects), so that there is more "above the fold" for the user to see, and not need to scroll down so much.
Also, we now have a reusable `FormButton` component that could be used to keep the buttons the same relative size/color
![Screenshot at 2019-05-21 20:26:15](https://user-images.githubusercontent.com/26943915/58137071-0743a600-7c07-11e9-9e0a-a5452ac68bbd.png)

## Current Behavior

At the moment there is just one column so the fields are too wide and a user must scroll down to see the buttons they can click on to create/edit a project.
Also, the `Create Project` button is directly beneath the other buttons and is more the color of our cancel buttons.
![Screenshot at 2019-05-21 20:25:26](https://user-images.githubusercontent.com/26943915/58137117-3ce88f00-7c07-11e9-87f9-75f283d64adb.png)
![Screenshot at 2019-05-21 20:25:37](https://user-images.githubusercontent.com/26943915/58137118-407c1600-7c07-11e9-927a-0d4d63cf743d.png)

## Possible Solution

We can make use of `Semantic UI`s `Grid` to create two columns each with their own fields
https://react.semantic-ui.com/collections/grid/
## Steps to Reproduce (for bugs)

1. go to `/events/new`
2. check out the form

**Comment by 47analogy** [comment]
Any requirements/guidance on how the final design should look? For example, if all the inputs are on the left and selectors are on the right, with the buttons at bottom of page:
---------------------------------------------------------------------------------------------------------------------------------------
### Title:                Status:                                 
### Img url:
### Description:
#### Create-button      Repo-button    Tracker-button
--------------------------------------------------------------------------------------------------------------------------------------

To even out the column lengths, maybe switch description with status? For the buttons, maybe have the two add buttons (on the same line) above the create project button?
