### ISSUE TITLE
Refactor some components to use react hooks.

### ISSUE THREAD

**Issue by Kachulio1** [AgileVentures/WebsiteOne-FE#32]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by mattwr18** [comment]
gonna close this for now as we would need to consider changing our testing framework since enzyme doesn't support testing react hooks at the moment
