### ISSUE TITLE
create a zeit.co av account

### ISSUE THREAD

**Issue by FedericoEsparza** [AgileVentures/WebsiteOne-FE#56]
create a zeit.co av account

**Comment by FedericoEsparza** [comment]
Does it support a custom url? Do we even need it?

**Comment by mattwr18** [comment]
> Does it support a custom url? Do we even need it?

I'm not sure if it does or not, at the moment it hasn't been configured... not sure if we need it right now...

**Comment by mattwr18** [comment]
https://zeit.co/blog/now-alias
